export enum BusinessErrorCode {
  NO_SERVICES = "NO_SERVICES",
  REQUIRES_REAUTH = "REQUIRES_REAUTH",
  NOT_ALLOWED_AFTER_AUTHORIZATION = "NOT_ALLOWED_AFTER_AUTHORIZATION",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
}
