export enum OrderEventType {
  ORDEN_CREADA = "ORDEN_CREADA",
  ORDEN_DIAGNOSTICADA = "ORDEN_DIAGNOSTICADA",
  ORDEN_AUTORIZADA = "ORDEN_AUTORIZADA",
  REAUTORIZADA = "REAUTORIZADA",
  ORDEN_EN_PROGRESO = "ORDEN_EN_PROGRESO",
  ORDEN_COMPLETADA = "ORDEN_COMPLETADA",
  ORDEN_ENTREGADA = "ORDEN_ENTREGADA",
  ORDEN_CANCELADA = "ORDEN_CANCELADA",
}
