export enum OrderStatus {
  CREATED = "CREATED",
  DIAGNOSED = "DIAGNOSED",
  AUTHORIZED = "AUTHORIZED",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL",
  COMPLETED = "COMPLETED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}
